throw()__custom_exception